### ISSUE TITLE
Debian Gnome/Wayland support

### ISSUE THREAD

**Issue by Miccio-AN** [linuxmint/wayland#101]
I installed sticky in Debian 12.6 with X11 and Gnome everything works great. Thanks!
However, if I use Wayland (always with Gnome) there are many problems starting up. 
In fact, the application is unusable.

Is there any fix planned?

**Comment by Spacedays** [comment]
I don't know how this app is supposed to typically function so try it yourself and see, but I'm able to run the app on Ubuntu 24.04 on wayland from the command line with sudo. Once I installed dbus-launch that seemed to enable some of the preferences and get rid of a bunch of warnings in the terminal. There's definitely still bugs, like a handful of the preferences don't work, but it seems to be usable.

FYI, Running without sudo does manage to launch the app for me, but it throws some errors related to GTK to the terminal and it also throws a GTK-related exception when trying to make a new note.
```
Traceback (most recent call last):  
  File "/usr/lib/sticky/sticky.py", line 1001, in new_note
      workarea_rect = Gdk.Monitor.get_workarea(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 0 does not allow None as a value
```

**Comment by Spacedays** [comment]
I don't know how this app is supposed to typically function so try it yourself and see, but I'm able to run the app on Ubuntu 24.04 on wayland from the command line with sudo. Once I installed dbus-launch that seemed to enable some of the preferences and get rid of a bunch of warnings in the terminal. There's definitely still bugs, like a handful of the preferences don't work, but it seems to be usable.

FYI, Running without sudo does manage to launch the app for me, but it throws some errors related to GTK to the terminal and it also throws a GTK-related exception when trying to make a new note.
```
Traceback (most recent call last):  
  File "/usr/lib/sticky/sticky.py", line 1001, in new_note
      workarea_rect = Gdk.Monitor.get_workarea(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 0 does not allow None as a value
```
