### ISSUE TITLE
Update manager freezes when installing HWE kernels

### ISSUE THREAD

**Issue by ghost** [linuxmint/wayland#39]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

AMD Ryzen 7 5700GE with Radeon Graphics

### Frequency

Always

### Bug description

When trying to install a newer kernel in Mint Update, the update manager freezes, cannot be closed, and does not install the newer kernel.

### Steps to reproduce

1. Open Mint Update.
2. Click view->Linux kernels
3. Click on the latest 6.5 kernel
4. Click install

### Expected behavior

The newer kernel should install.

### Additional information

a)I have tested this on a fresh virtual machine running in Gnome Boxes 45 (flatpak).
b)The bug is only present using Wayland.

**Comment by WhosyVox** [comment]
To add, the error occurs immediately after confirming to install the kernel.

* Open Update Manager 
* Open the kernel menu via `View > Linux Kernels` 
* Click `Continue` on the warning dialogue (if present)
* Select a not-yet installed kernel
* Click `Install`
* Answer `Yes` on the confirmation dialogue


From the terminal, the error output is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 64, in run
    "--non-interactive", "--parent-window-id", "%s" % self.application.window.get_window().get_xid(), \
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'. Did you mean 'get_width'?
```

The entire Update Manager window is then unresponsive, but can be closed via system tray applet.
